// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfpeeyodjginridkdjcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcGVleW9kamdpbnJpZGtkamNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxOTM1MzgsImV4cCI6MjA3Mjc2OTUzOH0.EtSttyCWRfBiN_t4aJ-aYrUtiIbWHFYQ8IiRgbrX-Ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});